// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Q-hGCPE1el_9FrxWhYZrASuAQ709YHE',
    appId: '1:1018551264650:web:b025fb2cdf41a8fd669473',
    messagingSenderId: '1018551264650',
    projectId: 'currency-converter-9f2a3',
    authDomain: 'currency-converter-9f2a3.firebaseapp.com',
    databaseURL: 'https://currency-converter-9f2a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'currency-converter-9f2a3.appspot.com',
    measurementId: 'G-K5YLWXBT1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvzNZJ2O10fDNPw3pBFWHrUt-WIg1IYrQ',
    appId: '1:1018551264650:android:8d27b9f934e3cf37669473',
    messagingSenderId: '1018551264650',
    projectId: 'currency-converter-9f2a3',
    databaseURL: 'https://currency-converter-9f2a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'currency-converter-9f2a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1foOdqhTkLcjN7V3jQIMkRHhZeFBL8Ss',
    appId: '1:1018551264650:ios:7209f819db58d20f669473',
    messagingSenderId: '1018551264650',
    projectId: 'currency-converter-9f2a3',
    databaseURL: 'https://currency-converter-9f2a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'currency-converter-9f2a3.appspot.com',
    iosBundleId: 'com.shishir.currencyConverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1foOdqhTkLcjN7V3jQIMkRHhZeFBL8Ss',
    appId: '1:1018551264650:ios:7209f819db58d20f669473',
    messagingSenderId: '1018551264650',
    projectId: 'currency-converter-9f2a3',
    databaseURL: 'https://currency-converter-9f2a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'currency-converter-9f2a3.appspot.com',
    iosBundleId: 'com.shishir.currencyConverter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Q-hGCPE1el_9FrxWhYZrASuAQ709YHE',
    appId: '1:1018551264650:web:04f3e5d833205081669473',
    messagingSenderId: '1018551264650',
    projectId: 'currency-converter-9f2a3',
    authDomain: 'currency-converter-9f2a3.firebaseapp.com',
    databaseURL: 'https://currency-converter-9f2a3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'currency-converter-9f2a3.appspot.com',
    measurementId: 'G-YN0NH92R35',
  );

}